<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- =============================================================================================================== -->
    <groupId>dev.shadmage</groupId>
    <artifactId>claimflygp</artifactId>
    <name>ClaimFlyGP</name>
    <version>2.2.5</version>
    <packaging>jar</packaging>
    <!-- =============================================================================================================== -->
    <properties>
        <author>shadmage</author>
        <main.class>dev.shadmage.claimflygp.ClaimFlyGPPlugin</main.class>
        <!-- =========================================================================================================== -->
        <foundation.version>6.10.1</foundation.version>
        <!-- https://github.com/kangarko/Foundation/releases -->
        <mavencompiler.version>3.15.0</mavencompiler.version>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <mavenshade.version>3.6.2</mavenshade.version>
        <!-- https://repository.apache.org/content/repositories/snapshots/org/apache/maven/plugins/maven-shade-plugin/ -->
        <mavenjarplugin.version>3.5.0</mavenjarplugin.version>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
        <griefprevention.version>16.18.4</griefprevention.version>
        <!-- https://github.com/TechFortress/GriefPrevention/releases -->
        <foundation.path>com.github.kangarko</foundation.path>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.helpch.at/releases/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.TechFortress</groupId>
            <artifactId>GriefPrevention</artifactId>
            <version>${griefprevention.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>${foundation.path}</groupId>
            <artifactId>Foundation</artifactId>
            <version>${foundation.version}</version>
        </dependency>

        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.12.2</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${mavenjarplugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${mavencompiler.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.46</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${mavenshade.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <artifactSet>
                        <includes>
                            <include>${foundation.path}:Foundation*</include>
                        </includes>
                    </artifactSet>
                    <relocations>
                        <!-- Move the Foundation library into your own package in "lib" subpackage to prevent interference. -->
                        <relocation>
                            <pattern>org.mineacademy.fo</pattern>
                            <shadedPattern>${project.groupId}.${project.artifactId}.lib</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>
