package dev.shadmage.claimflygp.policy;

public enum FlightReason {
	BYPASS,
	OWN_CLAIM,
	TRUSTED_CLAIM,
	ADMIN_CLAIM,
	UNCLAIMED,
	IGNORED_GAMEMODE,
	DENIED_WORLD_DISABLED,
	DENIED_NO_SERVER_PERMISSION,
	DENIED_OWN_CLAIM,
	DENIED_OTHER_CLAIM,
	DENIED_ADMIN_CLAIM,
	DENIED_UNCLAIMED
}
